

```{r}
library("tidyverse")
library(viridis)
library(scales)
library(ggh4x)
```

```{r Make folders}
ifelse(!dir.exists(paths = "../output/figs"), dir.create(file.path("../output/figs")), FALSE)

folder_names <- c("benchmarking_minimap", 
                  "benchmarking_strobemap",
                  "entropy_pmatch",
                  "matching_analysis_bio",
                  "matching_analysis_sim",
                  "uniqueness_esize")

for (folder_name in folder_names){
  ifelse(!dir.exists(paths = paste("../output/figs/", folder_name, sep="")),
       dir.create(file.path(paste("../output/figs/", folder_name, sep=""))),
       FALSE)
}
```

```{r Code for Fig. 1}

```

```{r Code for Fig. 2a}
results_entropy <- read.table("../output/data tables/p_match/fig2A_10000_30_25_50.csv", header=T, sep=",")
results_entropy$seeding <- factor(results_entropy$seeding, levels= c("k-mers", "minstrobes", "hybridstrobes", "randstrobes", "mixedstrobes", "altstrobes", "multistrobes")) 

ggplot(results_entropy)+
  geom_line(aes(x = m, y = N_m, col=seeding))+
  scale_x_continuous(breaks=c(1,5, 10, 15, 20, 25))+
  theme(legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 10))+
  guides(col = guide_legend(nrow = 3, byrow = TRUE))+
  labs(y=expression(P(N[m] > 0)))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "blue", "#E76BF3", "black"))

ggsave("../output/figs/entropy_pmatch/fig_2a_p_match-25-50.pdf", width = 4.25, height = 4)
ggsave("../output/figs/entropy_pmatch/fig_2a_p_match-25-50.png", width = 4.25, height = 4)
```
```{r}
results_entropy_all <- rbind(
  read.table("../output/data tables/p_match/10000_30_49_50_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_99_100_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_199_200_pypy.csv", header=T, sep=",")) %>% 
  mutate(type = ifelse(type == "mixed-randstrobes", "mixedstrobes", type),
         type = ifelse(type == "continous altstrobes", "multistrobes", type),
         window = paste("W = [", w_min, ",", w_max, "]", sep = ""),
         w_max = paste("w_max = ", w_max, sep=""))

results_entropy_all$w_min <- factor(results_entropy_all$w_min, levels = c(49, 99, 199))
results_entropy_all$type <- factor(results_entropy_all$type, levels= c("k-mers", "altstrobes", "randstrobes", "mixedstrobes", "multistrobes"))
results_entropy_all$window <- factor(results_entropy_all$window, levels = c("W = [49,50]", "W = [99,100]", "W = [199,200]"))
results_entropy_all$w_max <- factor(results_entropy_all$w_max, levels = c("w_max = 50", "w_max = 100", "w_max = 200"))

results_entropy_all <- results_entropy_all %>% mutate(x = ifelse(x == 30, 0, x))

ggplot(results_entropy_all %>% mutate(ymetric = ifelse(ymetric == "p_match", "Sensitivity", ymetric)), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.5)+
  geom_point(aes(x = x, y = y, fill = type, shape = window), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]               Fraction Strobemers             Length k[s]",
       y = "")+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_shape_manual(values = c(21,24,23,22,25))+
  facet_nested(w_max+ymetric ~ analysis, scales = "free")+
  expand_limits(x = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/supp_entropy_pmatch_small_window.png", width = 6, height = 10)
ggsave("../output/figs/entropy_pmatch/supp_entropy_pmatch_small_window.pdf", width = 6, height = 10)
```



```{r Code for Fig. 2b/c and Suppl. Fig. 1}
results_entropy_all <- rbind(
  read.table("../output/data tables/p_match/10000_30_16_50_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/10000_30_25_50_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/10000_30_35_50_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/10000_30_45_50_pypy.csv", header=T, sep=","),
  #read.table("../output/data tables/p_match/10000_30_49_50_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_16_100_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_25_100_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_50_100_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_75_100_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_95_100_pypy.csv", header=T, sep=","),
  #read.table("../output/data tables/p_match/1000_30_99_100_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_16_200_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_50_200_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_100_200_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_150_200_pypy.csv", header=T, sep=","),
  read.table("../output/data tables/p_match/1000_30_195_200_pypy.csv", header=T, sep=",")) %>% 
  #read.table("../output/data tables/p_match/1000_30_199_200_pypy.csv", header=T, sep=",")) %>% 
  mutate(type = ifelse(type == "mixed-randstrobes", "mixedstrobes", type),
         type = ifelse(type == "continous altstrobes", "multistrobes", type),
         window = paste("W = [", w_min, ",", w_max, "]", sep = ""),
         w_max = paste("w_max = ", w_max, sep="")) %>% 
  filter(type != "Optimal")

#results_entropy_all <- rbind(
#  results_entropy_all,
#  results_entropy_all %>% filter(type == "Optimal" & x == 30) %>% mutate(analysis = "mixedstrobes-analysis", x = 0),
#  results_entropy_all %>% filter(type == "Optimal" & x == 30) %>% mutate(analysis = "mixedstrobes-analysis", x = 1)
#)


# unique(results_entropy_all$w_max)             

results_entropy_all$w_min <- factor(results_entropy_all$w_min, levels = c(16, 25, 35, 45, 49, 50, 75, 95, 99, 100, 150, 195, 199))
#results_entropy_all$type <- factor(results_entropy_all$type, levels= c("Optimal", "k-mers", "altstrobes", "randstrobes", "mixedstrobes")) 
results_entropy_all$type <- factor(results_entropy_all$type, levels= c("k-mers", "altstrobes", "randstrobes", "mixedstrobes", "multistrobes"))
results_entropy_all$window <- factor(results_entropy_all$window, levels = c("W = [16,50]", "W = [25,50]", "W = [35,50]", "W = [45,50]", "W = [49,50]", "W = [16,100]", "W = [25,100]", "W = [50,100]", "W = [75,100]", "W = [95,100]", "W = [99,100]", "W = [16,200]", "W = [50,200]", "W = [100,200]", "W = [150,200]", "W = [195,200]", "W = [199,200]"))
results_entropy_all$w_max <- factor(results_entropy_all$w_max, levels = c("w_max = 50", "w_max = 100", "w_max = 200"))

results_entropy_all <- results_entropy_all %>% mutate(x = ifelse(x == 30, 0, x))

ggplot(results_entropy_all %>% filter(ymetric == "Entropy" & w_max == "w_max = 50"), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.25)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "none",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]                Fraction Strobemers                Length k[s]",
       y = "Entropy")+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_size_manual(values = c(1,1,1,1,1))+
  scale_shape_manual(values = c(21,24,23,22,25,18))+
  facet_grid(w_max ~ analysis, scales = "free")+
  expand_limits(x = 0, y = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/fig_2b_entropy50.png", width = 5.75, height = 2.5)
ggsave("../output/figs/entropy_pmatch/fig_2b_entropy50.pdf", width = 5.75, height = 2.5)

ggplot(results_entropy_all %>% filter(ymetric == "p_match" & w_max == "w_max = 50"), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.25)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "none",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]                Fraction Strobemers               Length k[s]",
       y = "Sensitivity")+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_shape_manual(values = c(21,24,23,22,25))+
  facet_grid(w_max ~ analysis, scales = "free")+
  expand_limits(x = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/fig_2c_p_match50.png", width = 5.75, height = 2.5)
ggsave("../output/figs/entropy_pmatch/fig_2c_p_match50.pdf", width = 5.75, height = 2.5)



ggplot(results_entropy_all %>% filter(w_max == "w_max = 50") %>% mutate(ymetric = ifelse(ymetric == "p_match", "Sensitivity", ymetric)), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.5)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]               Fraction Strobemers             Length k[s]",
       y = "")+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_shape_manual(values = c(21,24,23,22,25))+
  facet_nested(w_max+ymetric ~ analysis, scales = "free")+
  expand_limits(x = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/fig_2bc.png", width = 6, height = 4.5)
ggsave("../output/figs/entropy_pmatch/fig_2bc.pdf", width = 6, height = 4.5)
ggsave("../output/figs/entropy_pmatch/fig_2bc_RECOMB.pdf", width = 6, height = 4.0)


ggplot(results_entropy_all %>% filter(w_max != "w_max = 50") %>% mutate(ymetric = ifelse(ymetric == "p_match", "Sensitivity", ymetric)), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.5)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]               Fraction Strobemers             Length k[s]",
       y = "")+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_shape_manual(values = c(21,24,23,22,25,7,8,9))+
  facet_nested(w_max+ymetric ~ analysis, scales = "free")+
  expand_limits(x = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/supp_entropy_pmatch_100_200.png", width = 6, height = 8)
ggsave("../output/figs/entropy_pmatch/supp_entropy_pmatch_100_200.pdf", width = 6, height = 8)

ggplot(results_entropy_all %>% filter(ymetric == "Entropy" & w_max == "w_max = 100"), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.25)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]                            Fraction Strobemers                            Length k[s]",
       y = "Entropy")+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_size_manual(values = c(1,1,1,1))+
  scale_shape_manual(values = c(21,24,23,22,25,4))+
  facet_grid(w_max ~ analysis, scales = "free")+
  expand_limits(x = 0, y = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/supp_entropy100.png", width = 7, height = 4)
ggsave("../output/figs/entropy_pmatch/supp_entropy100.pdf", width = 7, height = 4)

ggplot(results_entropy_all %>% filter(ymetric == "p_match" & w_max == "w_max = 100"), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.25)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]                            Fraction Strobemers                            Length k[s]",
       y = "Sensitivity")+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_shape_manual(values = c(21,24,23,22,25,4))+
  facet_grid(w_max ~ analysis, scales = "free")+
  expand_limits(x = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/supp_p_match100.png", width = 7, height = 4)
ggsave("../output/figs/entropy_pmatch/supp_p_match100.pdf", width = 7, height = 4)


ggplot(results_entropy_all %>% filter(ymetric == "Entropy" & w_max == "w_max = 200"), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.25)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]                            Fraction Strobemers                            Length k[s]",
       y = "Entropy")+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_size_manual(values = c(1,1,1,1))+
  scale_shape_manual(values = c(21,24,23,22,25,4))+
  facet_grid(w_max ~ analysis, scales = "free")+
  expand_limits(x = 0, y = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/supp_entropy200.png", width = 7, height = 4)
ggsave("../output/figs/entropy_pmatch/supp_entropy200.pdf", width = 7, height = 4)

ggplot(results_entropy_all %>% filter(ymetric == "p_match" & w_max == "w_max = 200"), aes(group = interaction(w_min,type)))+
  geom_line(aes(x = x, y = y, col = type), size=0.25)+
  geom_point(aes(x = x, y = y, fill = type, shape = w_min), size = 2, stroke = 0.25)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  labs(x = "Length k[s]                            Fraction Strobemers                            Length k[s]",
       y = "Sensitivity")+
  scale_fill_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_shape_manual(values = c(21,24,23,22,25,4))+
  facet_grid(w_max ~ analysis, scales = "free")+
  expand_limits(x = 0)+
  guides(shape = guide_legend(order = 2),col = guide_legend(order = 1), size = "none", linetype = "none", fill = "none")
ggsave("../output/figs/entropy_pmatch/supp_p_match200.png", width = 7, height = 4)
ggsave("../output/figs/entropy_pmatch/supp_p_match200.pdf", width = 7, height = 4)


results_entropy_25_50 <- read.table("../output/data tables/p_match/10000_30_25_50_pypy.csv", header=T, sep=",") %>% 
  mutate(type = ifelse(type == "mixed-randstrobes", "mixedstrobes", type),
         type = ifelse(type == "continous altstrobes", "multistrobes", type),
         window = paste("W = [", w_min, ",", w_max, "]", sep = ""))

results_entropy_25_50 <- results_entropy_25_50 %>% mutate(x = ifelse(x == 30, 0, x))
results_entropy_25_50$type <- factor(results_entropy_25_50$type, levels= c("k-mers", "altstrobes", "randstrobes", "mixedstrobes", "multistrobes")) 

ggplot(results_entropy_25_50 %>% filter(ymetric == "Entropy"))+
  geom_point(aes(x = x, y = y, col = type, size = type))+
  geom_line(aes(x = x, y = y, col = type))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(x = "Length k[s]                  Fraction Strobemers                   Length k[s]",
       y = "Entropy")+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  scale_size_manual(values = c(1,1,1,1,1))+
  facet_grid(window ~ analysis, scales = "free")+
  expand_limits(x = 0, y = 0)
ggsave("../output/figs/entropy_pmatch/additional_entropy_25_50.png", width = 9, height = 3.5)
ggsave("../output/figs/entropy_pmatch/additional_entropy_25_50.pdf", width = 9, height = 3.5)

ggplot(results_entropy_25_50 %>% filter(ymetric == "p_match"))+
  geom_point(aes(x = x, y = y, col = type))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  labs(x = "Length k[s]                   Fraction Strobemers                   Length k[s]",
       y = expression(P(N[m])))+
  scale_color_manual(values = c("#F8766D", "#E76BF3", "#00B0F6", "blue", "black"))+
  facet_grid(window ~ analysis, scales = "free")+
  expand_limits(x = 0, y = 0)
ggsave("../output/figs/entropy_pmatch/additional_p_match_25_50.png", width = 9, height = 3.5)
ggsave("../output/figs/entropy_pmatch/additional_p_match_25_50.pdf", width = 9, height = 3.5)
```


```{r Code for Fig. 3 and Suppl. Fig. S5+S6}
kmers <- read.table("../output/data tables/matching_analysis_bio_collinear/kmers (Summary).txt", sep="&") %>% mutate(method = "kmers", strobe_fraction = 0)

mixedrandstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe10 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 10)
mixedrandstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe20 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 20)
mixedrandstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe30 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 30)
mixedrandstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe40 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 40)
mixedrandstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe50 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 50)
mixedrandstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe60 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 60)
mixedrandstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe70 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 70)
mixedrandstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe80 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 80)
mixedrandstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe90 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 90)
randstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/randstrobe (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 100)

mixedhybridstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe10 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 10)
mixedhybridstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe20 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 20)
mixedhybridstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe30 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 30)
mixedhybridstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe40 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 40)
mixedhybridstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe50 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 50)
mixedhybridstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe60 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 60)
mixedhybridstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe70 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 70)
mixedhybridstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe80 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 80)
mixedhybridstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe90 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 90)
hybridstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/hybridstrobe (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 100)

mixedminstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe10 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 10)
mixedminstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe20 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 20)
mixedminstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe30 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 30)
mixedminstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe40 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 40)
mixedminstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe50 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 50)
mixedminstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe60 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 60)
mixedminstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe70 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 70)
mixedminstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe80 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 80)
mixedminstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe90 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 90)
minstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/minstrobe (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 100)

mixedaltstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe10 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 10)
mixedaltstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe20 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 20)
mixedaltstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe30 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 30)
mixedaltstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe40 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 40)
mixedaltstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe50 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 50)
mixedaltstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe60 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 60)
mixedaltstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe70 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 70)
mixedaltstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe80 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 80)
mixedaltstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe90 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 90)
altstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/altstrobe (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 100)
multistrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/multistrobes (Summary).txt", sep="&") %>% mutate(method = "multistrobes", strobe_fraction = 100)

results_coll <- rbind(
  kmers, 
  mixedhybridstrobes10, mixedhybridstrobes20, mixedhybridstrobes30, mixedhybridstrobes40, mixedhybridstrobes50, 
  mixedhybridstrobes60, mixedhybridstrobes70, mixedhybridstrobes80, mixedhybridstrobes90, hybridstrobes,
  mixedminstrobes10, mixedminstrobes20, mixedminstrobes30, mixedminstrobes40, mixedminstrobes50, 
  mixedminstrobes60, mixedminstrobes70, mixedminstrobes80, mixedminstrobes90, minstrobes,
  mixedrandstrobes10, mixedrandstrobes20, mixedrandstrobes30, mixedrandstrobes40, mixedrandstrobes50, 
  mixedrandstrobes60, mixedrandstrobes70, mixedrandstrobes80, mixedrandstrobes90, randstrobes,
  mixedaltstrobes10, mixedaltstrobes20, mixedaltstrobes30, mixedaltstrobes40, #mixedaltstrobes50, 
  mixedaltstrobes60, mixedaltstrobes70, mixedaltstrobes80, mixedaltstrobes90, altstrobes, multistrobes
  ) %>% rename("query" = "V1", "length" = "V2", "mp" = "V3", "sc" = "V4", "mc" = "V5", "esize" = "V6", "coll_esize" = "V7")

results_coll$method <- factor(results_coll$method, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "multistrobes"))
results_coll

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = mp, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Length [bp]",
       y = "Matches [%]")+
  ylim(0, 15)
ggsave("../output/figs/matching_analysis_bio/supp_matches_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_matches_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = sc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Length [bp]",
       y = "Sequence Coverage [%]")+
  ylim(0, 100)
ggsave("../output/figs/matching_analysis_bio/supp_sequence_coverage_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_sequence_coverage_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = mc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Length [bp]",
       y = "Match Coverage [%]")+
  ylim(0, 100)
ggsave("../output/figs/matching_analysis_bio/supp_match_coverage_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_match_coverage_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = esize, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Length [bp]",
       y = "Expected Island Size [bp]")+
  ylim(0, 1200)
ggsave("../output/figs/matching_analysis_bio/supp_expected_island_size_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_expected_island_size_(2,15,25,50).pdf", height = 3, width = 3)


results_coll_rand_alt <- rbind(mixedrandstrobes80 %>% mutate(method = "mixedrandstrobes80"), randstrobes, altstrobes, multistrobes)%>% rename("query" = "V1", "length" = "V2", "mp" = "V3", "sc" = "V4", "mc" = "V5", "esize" = "V6", "coll_esize" = "V7")
results_coll_rand_alt$method <- factor(results_coll_rand_alt$method, levels =c("mixedrandstrobes80", "randstrobes", "altstrobes", "multistrobes"))

ggplot(results_coll_rand_alt, aes(x = length, y = mp, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3", "black"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid", "solid"))+ 
  labs(x = "Length [bp]",
       y = "Matches [%]")
ggsave("../output/figs/matching_analysis_bio/supp_matches_detail_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_matches_detail_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll_rand_alt, aes(x = length, y = sc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3", "black"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid", "solid"))+  
  labs(x = "Length [bp]",
       y = "Sequence Coverage [%]")
ggsave("../output/figs/matching_analysis_bio/supp_sequence_coverage_detail_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_sequence_coverage_detail_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll_rand_alt, aes(x = length, y = mc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3", "black"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid", "solid"))+  
  labs(x = "Length [bp]",
       y = "Match Coverage [%]")
ggsave("../output/figs/matching_analysis_bio/supp_match_coverage_detail_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_match_coverage_detail_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll_rand_alt, aes(x = length, y = esize, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3", "black"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid", "solid"))+ 
  scale_y_log10()+
  labs(x = "Length [bp]",
       y = "Expected Island Size [bp]")
ggsave("../output/figs/matching_analysis_bio/supp_expected_island_size_detail_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/supp_expected_island_size_detail_(2,15,25,50).pdf", height = 3, width = 3)


randstrobes <- randstrobes %>% separate(V1, c("V1", "nr"), sep = " ") %>% mutate(nr = as.integer(nr)+1) %>% unite(V1, V1:nr, sep = " ", remove = TRUE) %>% mutate(V1 = paste(V1,""))
mixedrandstrobes80 <- mixedrandstrobes80 %>% separate(V1, c("V1", "nr"), sep = " ") %>% mutate(nr = as.integer(nr)+1) %>% unite(V1, V1:nr, sep = " ", remove = TRUE) %>% mutate(V1 = paste(V1,""))

results_coll_comparison <- left_join(randstrobes, mixedrandstrobes80, by = c("V1", "V2")) %>% 
  left_join(altstrobes, by = c("V1", "V2")) %>% left_join(multistrobes, by = c("V1", "V2")) %>% 
  mutate(mp_mixed = V3.y/V3.x, mp_alt = V3.x.x/V3.x, mp_mult = V3.y.y/V3.x,
         sc_mixed = V4.y/V4.x, sc_alt = V4.x.x/V4.x, sc_mult = V4.y.y/V4.x,
         mc_mixed = V5.y/V5.x, mc_alt = V5.x.x/V5.x, mc_mult = V5.y.y/V5.x,
         esize_mixed = V6.y/V6.x, esize_alt = V6.x.x/V6.x, esize_mult = V6.y.y/V6.x) %>% 
  dplyr::select("length"=V2,mp_mixed, mp_alt, mp_mult, sc_mixed, sc_alt, sc_mult, mc_mixed, mc_alt, mc_mult, esize_mixed, esize_alt, esize_mult)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = mp_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mp_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = mp_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mp_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_point(aes(x = length, y = mp_mult), col = "black", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mp_mult), col = "black", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  #scale_y_continuous(trans = log2_trans(), breaks = c(0.9, 1.0, 1.1, 1.2, 1.3, 1.4))+
  labs(x = "Length [bp]",
       y = "Matches [normalized by randstrobes]")
ggsave("../output/figs/matching_analysis_bio/additional_matches_detail_normalized_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/additional_matches_detail_normalized_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = sc_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = sc_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = sc_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = sc_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_point(aes(x = length, y = sc_mult), col = "black", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = sc_mult), col = "black", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  #scale_y_continuous(trans = log2_trans(), breaks = c(0.9, 1.0, 1.1, 1.2, 1.3, 1.4))+
  labs(x = "Length [bp]",
       y = "Sequence Coverage [normalized by randstrobes]")
ggsave("../output/figs/matching_analysis_bio/additional_sequence_coverage_detail_normalized_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/additional_sequence_coverage_detail_normalized_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = mc_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mc_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = mc_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mc_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_point(aes(x = length, y = mc_mult), col = "black", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mc_mult), col = "black", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  #scale_y_continuous(trans = log2_trans(), breaks = c(0.8, 0.9, 1.0, 1.1, 1.2))+
  labs(x = "Length [bp]",
       y = "Match Coverage [normalized by randstrobes]")
ggsave("../output/figs/matching_analysis_bio/additional_match_coverage_detail_normalized_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/additional_match_coverage_detail_normalized_(2,15,25,50).pdf", height = 3, width = 3)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = esize_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = esize_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = esize_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = esize_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_point(aes(x = length, y = esize_mult), col = "black", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = esize_mult), col = "black", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  #scale_y_continuous(trans = log2_trans(), breaks = c(0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2))+
  labs(x = "Length [bp]",
       y = "Expected Island Size [normalized by randstrobes]")
ggsave("../output/figs/matching_analysis_bio/additional_expected_island_size_detail_normalized_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/additional_expected_island_size_detail_normalized_(2,15,25,50).pdf", height = 3, width = 3)


n_protocol <- results_coll %>% group_by(method, strobe_fraction) %>% summarise(tot_length = sum(length))

results_coll_summarized <- results_coll %>% 
  mutate(mp = mp * length, sc = sc * length, mc = mc * length, esize = esize * length) %>% 
  group_by(method, strobe_fraction) %>% summarise(length = mean(length), mp = sum(mp), sc = sum(sc), mc = sum(mc), esize = sum(esize)) %>% 
  left_join(n_protocol, by=c("method", "strobe_fraction")) %>% 
  mutate(mp = mp/tot_length, sc = sc/tot_length, mc = mc/tot_length, esize = esize/tot_length)
results_coll_summarized$method <- factor(results_coll_summarized$method, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "multistrobes"))

results_coll_summarized %>% filter(strobe_fraction == 0 | strobe_fraction == 100)
results_coll_summarized %>% filter(method == "altstrobes")

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = mp, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = mp, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")
ggsave("../output/figs/matching_analysis_bio/fig_3a_matches_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/fig_3a_matches_(2,15,25,50).pdf", height = 3, width = 3)

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = sc, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = sc, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")
ggsave("../output/figs/matching_analysis_bio/fig_3b_sequence_coverage_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/fig_3b_sequence_coverage_(2,15,25,50).pdf", height = 3, width = 3)

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = mc, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = mc, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")
ggsave("../output/figs/matching_analysis_bio/fig_3c_match_coverage_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/fig_3c_match_coverage_(2,15,25,50).pdf", height = 3, width = 3)

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = esize, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = esize, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size")
ggsave("../output/figs/matching_analysis_bio/fig_3d_expected_island_size_(2,15,25,50).png", height = 3, width = 3)
ggsave("../output/figs/matching_analysis_bio/fig_3d_expected_island_size_(2,15,25,50).pdf", height = 3, width = 3)
```


```{r Code for Fig. 4}
results_esize <- read.table(file = "../output/data tables/esize", header = TRUE, sep = ",") %>% mutate(datastructure = ifelse(datastructure == "mixedrandstrobes", "mixedstrobes", datastructure))
results_esize$datastructure = factor(results_esize$datastructure, levels=c('kmers', 'randstrobes', 'mixedstrobes', 'altstrobes', 'multistrobes'))

ggplot(results_esize)+
  geom_line(aes(x = k, y = ehits, col = datastructure, linetype = datastructure))+
  geom_point(aes(x = k, y = ehits, col = datastructure, shape = datastructure))+
  scale_linetype_manual(values=c("solid", "longdash", "longdash", "longdash", "longdash"))+
  scale_shape_manual(values = c(16,24,24,25,19))+
  scale_color_manual(values = c("#F8766D", "#00B0F6", "blue", "#E76BF3", "black"))+
  theme(strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11))+
  guides(linetype = guide_legend(nrow = 2, byrow = TRUE))+
  ylab("E-hits")+
  scale_x_continuous(limits = c(18, 36))+
  scale_y_log10(breaks = c(10,20,30,40,50)) 

ggsave("../output/figs/uniqueness_esize/fig_2_ehits.png", width = 4.25, height = 4)
ggsave("../output/figs/uniqueness_esize/fig_2_ehits.pdf", width = 4.25, height = 4)
```

```{r Code for Suppl. Fig. S2}
altstrobes_uniqueness <- read.table("../output/data tables/altstrobes10000_uniqueness", sep = ";", header = F) %>% 
  mutate(V1 = ifelse(V1 == "altstrobes2", "altstrobes", V1),
         V1 = ifelse(V1 == "randstrobes2", "randstrobes", V1)) %>% dplyr::rename("seeding" = "V1")
altstrobes_uniqueness$V2 <- factor(altstrobes_uniqueness$V2, levels = altstrobes_uniqueness$V2)

ggplot(altstrobes_uniqueness, aes(x=V2, y=V3, group=1))+
  geom_point(aes(col = seeding), stat='summary', fun.y=sum, size = 2.5)+
  stat_summary(aes(col = seeding), fun.y=sum, geom="line")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "bottom",
        legend.title = element_blank())+
  scale_color_manual(values = c("#E76BF3", "#F8766D", "#00B0F6"))+
  xlab("k")+
  ylab("% unique")+
  ylim(0,100)
ggsave("../output/figs/uniqueness_esize/supp_altstrobe_uniqueness.png", width = 4.5, height = 3)
ggsave("../output/figs/uniqueness_esize/supp_altstrobe_uniqueness.pdf", width = 4.5, height = 3)
```


```{r Code for Suppl. Fig. S3}
altstrobes_raw_data <- read.table(file = "../output/data tables/altstrobes", sep = "&", header = F)
altstrobes_raw_data

results_sim_alt <- altstrobes_raw_data %>% group_by(V1, V2, V7) %>% summarise(m = round(mean(V3),2), sc = round(mean(V4),2), mc = round(mean(V5),2), esize = round(mean(V6),2))
results_sim_alt

colnames(results_sim_alt) <- c("protocol", "strobe_lengths", "mutation_rate", "matches", "sequence_coverage", "match_coverage", "gaps")
results_sim_alt$strobe_lengths <- factor(results_sim_alt$strobe_lengths, levels = c(" (1/29) ", " (2/28) ", " (3/27) ", " (4/26) ", " (5/25) ", " (6/24) ", " (7/23) ", " (8/22) ", " (9/21) ", " (10/20) ", " (11/19) ", " (12/18) ", " (13/17) ", " (14/16) ", " (15/15) "))
results_sim_alt <- results_sim_alt %>% mutate(protocol = ifelse(strobe_lengths == " (15/15) ", "randstrobes", protocol))

p <- ggplot(results_sim_alt, aes(x = strobe_lengths, y = matches, group=1))+
  geom_point(aes(col = protocol))+
  geom_line()+
  stat_summary(geom = "line", col = "#E76BF3")+
  scale_color_manual(values = c("#E76BF3", "#00B0F6"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  labs(x = "Strobe Length",
       y = "Matches [%]")+
  facet_wrap(~mutation_rate, scales = "free")

ggsave("../output/figs/matching_analysis_sim/supp_matches_altstrobes.png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/supp_matches_altstrobes.pdf", height = 2.5, width = 7)

p <- ggplot(results_sim_alt, aes(x = strobe_lengths, y = sequence_coverage, group=1))+
  geom_point(aes(col = protocol))+
  geom_line()+
  stat_summary(geom = "line", col = "#E76BF3")+
  scale_color_manual(values = c("#E76BF3", "#00B0F6"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  labs(x = "Strobe Length",
       y = "Sequence Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")

ggsave("../output/figs/matching_analysis_sim/supp_sequence_coverage_altstrobes.png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/supp_sequence_coverage_altstrobes.pdf", height = 2.5, width = 7)

p <- ggplot(results_sim_alt, aes(x = strobe_lengths, y = match_coverage, group=1))+
  geom_point(aes(col = protocol))+
  geom_line()+
  stat_summary(geom = "line", col = "#E76BF3")+
  scale_color_manual(values = c("#E76BF3", "#00B0F6"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  labs(x = "Strobe Length",
       y = "Match Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")

ggsave("../output/figs/matching_analysis_sim/supp_match_coverage_altstrobes.png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/supp_match_coverage_altstrobes.pdf", height = 2.5, width = 7)

p <- ggplot(results_sim_alt, aes(x = strobe_lengths, y = gaps, group=1))+
  geom_point(aes(col = protocol))+
  geom_line()+
  stat_summary(geom = "line", col = "#E76BF3")+
  scale_color_manual(values = c("#E76BF3", "#00B0F6"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  labs(x = "Strobe Length",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")

ggsave("../output/figs/matching_analysis_sim/supp_expected_island_size_altstrobes.png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/supp_expected_island_size_altstrobes.pdf", height = 2.5, width = 7)
```

```{r Code for Suppl. Fig. S4}
results_sim <- read.table(file = "../output/data tables/matching_analysis_simulated (2,15,25,50)", sep = "&", header = F)
colnames(results_sim) <- c("protocol", "order", "setting", "strobe_fraction", "matches", "sequence_coverage", "match_coverage", "gaps", "mutation_rate")
results_sim <- results_sim %>% mutate(protocol = gsub("mixed", "", protocol))
results_sim <- results_sim %>% group_by(protocol, order, strobe_fraction, mutation_rate) %>% 
  summarise(matches = mean(matches), sequence_coverage = mean(sequence_coverage), match_coverage = mean(match_coverage), gaps = mean(gaps))
results_sim$protocol <- factor(results_sim$protocol, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse", "multistrobes"))
results_sim <- results_sim %>% filter(protocol != "altstrobes" | strobe_fraction != 0.5)
results_sim

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")))+
  geom_point(aes(x = 100*strobe_fraction, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")+
  facet_grid(mutation_rate~order, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/matching_analysis_sim/supp_matches_sim_all_(2,15,25,50).png", height = 4.75, width = 5)
ggsave("../output/figs/matching_analysis_sim/supp_matches_sim_all_(2,15,25,50).pdf", height = 4.75, width = 5)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) )+
  geom_point(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")+
  facet_grid(mutation_rate~order, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/supp_sequence_coverage_sim_all_(2,15,25,50).png", height = 4.75, width = 5)
ggsave("../output/figs/matching_analysis_sim/supp_sequence_coverage_sim_all_(2,15,25,50).pdf", height = 4.75, width = 5)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) )+
  geom_point(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")+
  facet_grid(mutation_rate~order, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/supp_match_coverage_sim_all_(2,15,25,50).png", height = 4.75, width = 5)
ggsave("../output/figs/matching_analysis_sim/supp_match_coverage_sim_all_(2,15,25,50).pdf", height = 4.75, width = 5)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) )+
  geom_point(aes(x = 100*strobe_fraction, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size [bp]")+
  facet_grid(mutation_rate~order, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/supp_expected_island_size_sim_all_(2,15,25,50).png", height = 4.75, width = 5)
ggsave("../output/figs/matching_analysis_sim/supp_expected_island_size_sim_all_(2,15,25,50).pdf", height = 4.75, width = 5)


p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_(2,15,25,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_(2,15,25,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_(2,15,25,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_(2,15,25,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_(2,15,25,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_(2,15,25,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,21))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "black"))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_(2,15,25,50).pdf", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_(2,15,25,50).png", height = 3, width = 7)
```


```{r Code for Suppl. Fig. S4}
results_sim <- read.table(file = "../output/data tables/matching_analysis_simulated_(2,15,16,50)", sep = "&", header = F)
colnames(results_sim) <- c("protocol", "order", "setting", "strobe_fraction", "matches", "sequence_coverage", "match_coverage", "gaps", "mutation_rate")
results_sim <- results_sim %>% mutate(protocol = gsub("mixed", "", protocol))
results_sim$protocol <- factor(results_sim$protocol, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse"))
results_sim <- results_sim %>% filter(protocol != "altstrobes" | strobe_fraction != 0.5)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_(2,15,16,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_(2,15,16,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_(2,15,16,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_(2,15,16,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_(2,15,16,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_(2,15,16,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_(2,15,16,50).pdf", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_(2,15,16,50).png", height = 3, width = 7)
```


```{r Code for Suppl. Fig. S4}
results_sim_subs_only <- read.table(file = "../output/data tables/matching_analysis_simulated_subs_only (2,15,25,50)", sep = "&", header = F)
colnames(results_sim_subs_only) <- c("protocol", "order", "setting", "strobe_fraction", "matches", "sequence_coverage", "match_coverage", "gaps", "mutation_rate")
results_sim_subs_only <- results_sim_subs_only %>% mutate(protocol = gsub("mixed", "", protocol))
results_sim_subs_only <- results_sim_subs_only %>% group_by(protocol, order, strobe_fraction, mutation_rate) %>% 
  summarise(matches = mean(matches), sequence_coverage = mean(sequence_coverage), match_coverage = mean(match_coverage), gaps = mean(gaps))
results_sim_subs_only$protocol <- factor(results_sim_subs_only$protocol, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse"))
results_sim_subs_only <- results_sim_subs_only %>% filter(protocol != "altstrobes" | strobe_fraction != 0.5)
results_sim_subs_only


p <- ggplot(results_sim_subs_only %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,17,18))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "gray20", "grey60"))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_subs_only_(2,15,25,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_subs_only_(2,15,25,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim_subs_only %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,17,18))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "gray20", "grey60"))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_subs_only_(2,15,25,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_subs_only_(2,15,25,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim_subs_only %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,17,18))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "gray20", "grey60"))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_subs_only_(2,15,25,50).png", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_subs_only_(2,15,25,50).pdf", height = 3, width = 7)

p <- ggplot(results_sim_subs_only %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25,17,18))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3", "gray20", "grey60"))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_subs_only_(2,15,25,50).pdf", height = 3, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_subs_only_(2,15,25,50).png", height = 3, width = 7)
```


```{r Code for Suppl. Fig. S7}
results_uniqueness <- read.table(file = "../output/data tables/uniqueness.csv", header = TRUE, sep = ",")
results_uniqueness_mixed <- results_uniqueness %>% filter(!Method %in% c("kmers", "multistrobes2")) %>% separate(Method, c("Method", "Order"), sep="(?<=strobes)") %>% mutate(Order = paste("Order",Order))
results_uniqueness_mixed$Method = factor(results_uniqueness_mixed$Method, levels=c('mixedminstrobes', 'mixedhybridstrobes', 'mixedrandstrobes', 'mixedaltstrobes'))



ggplot(results_uniqueness_mixed)+
  geom_line(aes(x = k, y = unique, group= strobefraction, col = strobefraction))+
  theme(legend.position = "bottom")+
  facet_grid(Order ~ Method)+
  scale_color_viridis(discrete = FALSE, option = "B")+
  ylab("% unique")+
  scale_x_continuous(limits = c(18, 36))

ggsave("../output/figs/uniqueness_esize/supp_uniqueness_mixed.png", width = 5.3, height = 5)
ggsave("../output/figs/uniqueness_esize/supp_uniqueness_mixed.pdf", width = 5.3, height = 5)

results_uniqueness2 <- results_uniqueness %>% filter(Method == "kmers" | strobefraction == 100) %>% mutate(Method = str_replace(Method, "mixed",""))
results_uniqueness2$Method = factor(results_uniqueness2$Method, levels=c('kmers', 'minstrobes2', 'minstrobes3', 'hybridstrobes2', 'hybridstrobes3', 'randstrobes2', 'randstrobes3', 'altstrobes2', 'multistrobes2'))                                                                                                           

ggplot(results_uniqueness2)+
  geom_line(aes(x = k, y = unique, col = Method, linetype = Method))+
  geom_point(aes(x = k, y = unique, col = Method, shape = Method))+
  theme(legend.position = "bottom",
        legend.title = element_blank())+
  guides(linetype = guide_legend(nrow = 3, byrow = TRUE))+
  scale_linetype_manual(values=c("solid", "longdash", "dotted", "longdash", "dotted", "longdash", "dotted", "longdash", "longdash"))+
  scale_color_manual(values=c("#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC", "black"))+
  scale_shape_manual(values = c(16,22,22,23,23,24,24,25,19))+
  ylab("% unique")+
  scale_x_continuous(limits = c(18, 36))

ggsave("../output/figs/uniqueness_esize/supp_uniqueness_overview.png", width = 4, height = 4.5)
ggsave("../output/figs/uniqueness_esize/supp_uniqueness_overview.pdf", width = 4, height = 4.5)
```


```{r Code for Suppl. Fig. S8}
results_benchmarking_strobemap <- read.table("../output/data tables/benchmark_strobemap_indexing", header=T, sep="&", dec = ".", check.names = FALSE)
plotted_variables <- c("Total indexing time [s]", "Total time generating mers [s]", "Total size of hash table index [Mb]")

results_benchmarking_strobemap$seeding <- factor(results_benchmarking_strobemap$seeding, levels = c("k-mers", "randstrobes", "mixedstrobes", "altstrobes", "multistrobes"))
results_benchmarking_strobemap_melted <- reshape2::melt(results_benchmarking_strobemap, id = c("setting", "genome", "seeding"))
results_benchmarking_strobemap_melted$variable <- factor(results_benchmarking_strobemap_melted$variable, 
                                                         levels=c(
                                                          "Total indexing time [s]",
                                                          "Total time generating mers [s]",
                                                          "Total time generating flat index vector [s]",
                                                          "Total time generating hash table [s]",
                                                          "Maximum resident set size [Mb]",
                                                          "Total size of flat mers-vector [Mb]",
                                                          "Total size of hash table index [Mb]"
                                                          ))
results_benchmarking_strobemap_melted <- results_benchmarking_strobemap_melted %>% filter(variable %in% plotted_variables)

ggplot(results_benchmarking_strobemap_melted %>% filter(genome == "Human Chr.21"))+
  geom_col(aes(x = seeding, y = value/10, fill=seeding))+
  scale_fill_manual(values = c("#F8766D", "#00B0F6", "blue", "#E76BF3", "black"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none")+
  facet_grid(variable~genome, labeller = label_wrap_gen(width=14), scales="free_y")
ggsave("../output/figs/benchmarking_strobemap/supp_benchmarking_strobemap_human.pdf", width = 3.55, height = 4)
ggsave("../output/figs/benchmarking_strobemap/supp_benchmarking_strobemap_human.png", width = 3.55, height = 4)

ggplot(results_benchmarking_strobemap_melted %>% filter(genome == "E.coli"))+
  geom_col(aes(x = seeding, y = value/10, fill=seeding))+
  scale_fill_manual(values = c("#F8766D", "#00B0F6", "blue", "#E76BF3", "black"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none")+
  facet_grid(variable~genome, labeller = label_wrap_gen(width=14), scales="free_y")
ggsave("../output/figs/benchmarking_strobemap/supp_benchmarking_strobemap_ecoli.pdf", width = 3.5, height = 4)
ggsave("../output/figs/benchmarking_strobemap/supp_benchmarking_strobemap_ecoli.png", width = 3.5, height = 4)
```



```{r Code for Suppl. Fig. S9}
results_minimap <- read.table("../output/data tables/minimap_results", header=T, sep="&", dec = ".", check.names = FALSE)

results_minimap_melted <- reshape2::melt(results_minimap %>% unite("seeding", "seeding":"settings", remove = TRUE, sep = " "), id=c("seeding", "mut_freq"))
results_minimap_melted$seeding <- factor(results_minimap_melted$seeding, levels = c("altstrobes (2,9,18,25,50)", "kmers (15)", "kmers (28)", "mixedstrobes (2,14,25,50,0.8)", "randstrobes (2,14,25,50)", "multistrobes (2,6,22,25,50)"))

ggplot(results_minimap_melted)+
  geom_point(aes(x=seeding, y=value, col=seeding), size = 2)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none")+
  #scale_fill_manual(values = c("#E76BF3", "#F8766D", "#F8766D", "blue", "#00B0F6", "black"))+
  scale_color_manual(values = c("#E76BF3", "#F8766D", "#F8766D", "blue", "#00B0F6", "black"))+
  facet_grid(variable ~ mut_freq, scales = "free")
ggsave("../output/figs/benchmarking_minimap/supp_minimap.pdf", width = 7, height = 18)


unique(results_minimap_melted$variable)
variable_plotted = c("total time [s]", "indexing time [s]", "aligning time [s]", "peak RSS [Gb]", "mapped correctly [%]")

ggplot(results_minimap_melted %>% filter(variable %in% variable_plotted))+
  geom_point(aes(x=seeding, y=value, col=seeding), size = 2)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none")+
  #scale_fill_manual(values = c("#E76BF3", "#F8766D", "#F8766D", "blue", "#00B0F6", "black"))+
  scale_color_manual(values = c("#E76BF3", "#F8766D", "#F8766D", "blue", "#00B0F6", "black"))+
  facet_grid(variable ~ mut_freq, scales = "free")
ggsave("../output/figs/benchmarking_minimap/supp_minimap_1.pdf", width = 5.5, height = 9)


ggplot(results_minimap_melted %>% filter(!variable %in% variable_plotted))+
  geom_point(aes(x=seeding, y=value, col=seeding), size = 2)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none")+
  #scale_fill_manual(values = c("#E76BF3", "#F8766D", "#F8766D", "blue", "#00B0F6", "black"))+
  scale_color_manual(values = c("#E76BF3", "#F8766D", "#F8766D", "blue", "#00B0F6", "black"))+
  facet_grid(variable ~ mut_freq, scales = "free")
ggsave("../output/figs/benchmarking_minimap/supp_minimap_2.pdf", width = 5.5, height = 9)
```



```{r}
matching_analysis_simulated_detailed <- read.table("../output/data tables/matching_analysis_simulated_detailed (2,15,25,50)", header=F, sep="&", dec = ".")
colnames(matching_analysis_simulated_detailed) <- c("protocol", "order", "setting", "strobe_fraction", "matches", "sequence_coverage", "match_coverage", "gaps", "mutation_rate", "subs_freq")
matching_analysis_simulated_detailed <- matching_analysis_simulated_detailed %>% mutate(protocol = gsub("mixedrandstrobes", "mixedstrobes", protocol))
matching_analysis_simulated_detailed$protocol <- factor(matching_analysis_simulated_detailed$protocol, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "mixedstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse", "multistrobes"))
matching_analysis_simulated_detailed <- matching_analysis_simulated_detailed %>% filter(protocol != "mixedstrobes" | strobe_fraction == 0.8)
matching_analysis_simulated_detailed


p <- ggplot(matching_analysis_simulated_detailed %>% filter(order == 2) )+
  geom_point(aes(x = 100*subs_freq, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*subs_freq, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,24,25,17,18,19))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "blue", "#E76BF3", "gray40", "grey60", "black"))+
  labs(x = "Substitution Frequency [%]",
       y = "Matches [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_subs_(2,15,25,50).png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_matches_order2_subs_(2,15,25,50).pdf", height = 2.5, width = 7)

p <- ggplot(matching_analysis_simulated_detailed %>% filter(order == 2) )+
  geom_point(aes(x = 100*subs_freq, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*subs_freq, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,24,25,17,18,19))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "blue", "#E76BF3", "gray40", "grey60", "black"))+
  labs(x = "Substitution Frequency [%]",
       y = "Sequence Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_subs_(2,15,25,50).png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_sequence_coverage_order2_subs_(2,15,25,50).pdf", height = 2.5, width = 7)

p <- ggplot(matching_analysis_simulated_detailed %>% filter(order == 2) )+
  geom_point(aes(x = 100*subs_freq, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*subs_freq, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,24,25,17,18,19))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "blue", "#E76BF3", "gray40", "grey60", "black"))+
  labs(x = "Substitution Frequency [%]",
       y = "Match Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_subs_(2,15,25,50).png", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_match_coverage_order2_subs_(2,15,25,50).pdf", height = 2.5, width = 7)

p <- ggplot(matching_analysis_simulated_detailed %>% filter(order == 2) )+
  geom_point(aes(x = 100*subs_freq, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*subs_freq, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,24,25,17,18,19))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "blue", "#E76BF3", "gray40", "grey60", "black"))+
  labs(x = "Substitution Frequency [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_subs_(2,15,25,50).pdf", height = 2.5, width = 7)
ggsave("../output/figs/matching_analysis_sim/additional_expected_island_size_order2_subs_(2,15,25,50).png", height = 2.5, width = 7)
```


```{r}
p <- ggplot(matching_analysis_simulated_detailed %>% filter(order == 2) )+
  geom_point(aes(x = 100*subs_freq, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*subs_freq, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(strip.text.x = element_text(size = 11),
        strip.text.y = element_text(size = 11),
        legend.position = "bottom",
        legend.box="vertical",
        legend.title=element_blank(),
        legend.text = element_text(size = 11),
        legend.margin=margin())+
  scale_shape_manual(values = c(16,22,23,24,24,25,17,18,19))+
  scale_color_manual(values = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "blue", "#E76BF3", "gray40", "grey60", "black"))+
  labs(x = "Substitution Frequency [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("~/Desktop/fig3_legend.png", height = 3.75, width = 8)
```

