#!/usr/bin/env bash 

# 0
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0

# 0.1
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.1
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.1

# 0.2
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.2
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.2

# 0.3
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.3
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.3

# 0.4
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.4
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.4

# 0.5
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.5
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.5

# 0.6
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.6
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.6

# 0.7
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.7
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.7

# 0.8
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.8
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.8

# 0.9
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 0.9
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 0.9

# 1
python3 matching_analysis_simulated.py --method kmers --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method spaced_kmers_dense --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method spaced_kmers_sparse --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method minstrobes --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method randstrobes --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method hybridstrobes --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method altstrobes --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --method mixedrandstrobes --experiment_type specified --subs_freq 1
python3 matching_analysis_simulated.py --multistrobes --experiment_type specified --k_boundary 5 --subs_freq 1
