---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
library(scales)
```

```{r}
kmers <- read.table("../output/data tables/matching_analysis_bio_collinear/kmers (Summary).txt", sep="&") %>% mutate(method = "kmers", strobe_fraction = 0)

mixedrandstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe10 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 10)
mixedrandstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe20 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 20)
mixedrandstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe30 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 30)
mixedrandstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe40 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 40)
mixedrandstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe50 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 50)
mixedrandstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe60 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 60)
mixedrandstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe70 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 70)
mixedrandstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe80 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 80)
mixedrandstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedrandstrobe90 (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 90)
randstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/randstrobe (Summary).txt", sep="&") %>% mutate(method = "randstrobes", strobe_fraction = 100)

mixedhybridstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe10 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 10)
mixedhybridstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe20 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 20)
mixedhybridstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe30 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 30)
mixedhybridstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe40 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 40)
mixedhybridstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe50 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 50)
mixedhybridstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe60 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 60)
mixedhybridstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe70 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 70)
mixedhybridstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe80 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 80)
mixedhybridstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedhybridstrobe90 (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 90)
hybridstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/hybridstrobe (Summary).txt", sep="&") %>% mutate(method = "hybridstrobes", strobe_fraction = 100)

mixedminstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe10 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 10)
mixedminstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe20 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 20)
mixedminstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe30 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 30)
mixedminstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe40 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 40)
mixedminstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe50 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 50)
mixedminstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe60 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 60)
mixedminstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe70 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 70)
mixedminstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe80 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 80)
mixedminstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedminstrobe90 (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 90)
minstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/minstrobe (Summary).txt", sep="&") %>% mutate(method = "minstrobes", strobe_fraction = 100)

mixedaltstrobes10 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe10 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 10)
mixedaltstrobes20 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe20 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 20)
mixedaltstrobes30 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe30 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 30)
mixedaltstrobes40 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe40 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 40)
mixedaltstrobes50 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe50 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 50)
mixedaltstrobes60 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe60 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 60)
mixedaltstrobes70 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe70 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 70)
mixedaltstrobes80 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe80 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 80)
mixedaltstrobes90 <- read.table("../output/data tables/matching_analysis_bio_collinear/mixedaltstrobe90 (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 90)
altstrobes <- read.table("../output/data tables/matching_analysis_bio_collinear/altstrobe (Summary).txt", sep="&") %>% mutate(method = "altstrobes", strobe_fraction = 100)
```


```{r}
results_coll <- rbind(
  kmers, 
  mixedhybridstrobes10, mixedhybridstrobes20, mixedhybridstrobes30, mixedhybridstrobes40, mixedhybridstrobes50, 
  mixedhybridstrobes60, mixedhybridstrobes70, mixedhybridstrobes80, mixedhybridstrobes90, hybridstrobes,
  mixedminstrobes10, mixedminstrobes20, mixedminstrobes30, mixedminstrobes40, mixedminstrobes50, 
  mixedminstrobes60, mixedminstrobes70, mixedminstrobes80, mixedminstrobes90, minstrobes,
  mixedrandstrobes10, mixedrandstrobes20, mixedrandstrobes30, mixedrandstrobes40, mixedrandstrobes50, 
  mixedrandstrobes60, mixedrandstrobes70, mixedrandstrobes80, mixedrandstrobes90, randstrobes,
  mixedaltstrobes10, mixedaltstrobes20, mixedaltstrobes30, mixedaltstrobes40, #mixedaltstrobes50, 
  mixedaltstrobes60, mixedaltstrobes70, mixedaltstrobes80, mixedaltstrobes90, altstrobes
  ) %>% rename("query" = "V1", "length" = "V2", "mp" = "V3", "sc" = "V4", "mc" = "V5", "esize" = "V6", "coll_esize" = "V7")

results_coll$method <- factor(results_coll$method, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse"))

results_coll
```



```{r}
ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = mp, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  labs(x = "Length [bp]",
       y = "Matches [%]")+
  ylim(0, 65)
ggsave("../output/figs/[Fig4] Matches.png", height = 3, width = 3)

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = sc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  labs(x = "Length [bp]",
       y = "Sequence Coverage [%]")+
  ylim(0, 100)
ggsave("../output/figs/[Fig4] Sequence Coverage.png", height = 3, width = 3)

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = mc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  labs(x = "Length [bp]",
       y = "Match Coverage [%]")+
  ylim(0, 100)
ggsave("../output/figs/[Fig4] Match Coverage.png", height = 3, width = 3)

ggplot(results_coll %>% filter(strobe_fraction == 0 | strobe_fraction == 100), aes(x = length, y = esize, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.6, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  labs(x = "Length [bp]",
       y = "Expected Island Size [bp]")+
  ylim(0, 1200)
ggsave("../output/figs/[Fig4] Expected Island Size.png", height = 3, width = 3)
```

```{r}
results_coll_rand_alt <- rbind(mixedrandstrobes70 %>% mutate(method = "mixedrandstrobes70"), randstrobes, altstrobes)%>% rename("query" = "V1", "length" = "V2", "mp" = "V3", "sc" = "V4", "mc" = "V5", "esize" = "V6", "coll_esize" = "V7")
results_coll_rand_alt$method <- factor(results_coll_rand_alt$method, levels =c("mixedrandstrobes70", "randstrobes", "altstrobes"))

ggplot(results_coll_rand_alt, aes(x = length, y = mp, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid"))+ 
  labs(x = "Length [bp]",
       y = "Matches [%]")
ggsave("../output/figs/[Fig4.1] Matches.png", height = 3, width = 3)

ggplot(results_coll_rand_alt, aes(x = length, y = sc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid"))+ 
  labs(x = "Length [bp]",
       y = "Sequence Coverage [%]")
ggsave("../output/figs/[Fig4.1] Sequence Coverage.png", height = 3, width = 3)

ggplot(results_coll_rand_alt, aes(x = length, y = mc, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid"))+ 
  labs(x = "Length [bp]",
       y = "Match Coverage [%]")
ggsave("../output/figs/[Fig4.1] Match Coverage.png", height = 3, width = 3)

ggplot(results_coll_rand_alt, aes(x = length, y = esize, col = method))+
  geom_point(size= 0.2, alpha = 0.2)+
  geom_smooth(size = 0.4, se = F)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_color_manual(values = c("blue", "#00B0F6", "#E76BF3"))+
  scale_linetype_manual(values = c("dotted", "solid", "solid"))+
  scale_y_log10()+
  labs(x = "Length [bp]",
       y = "Expected Island Size [bp]")
ggsave("../output/figs/[Fig4.1] Expected Island Size.png", height = 3, width = 3)
```




```{r}
results_coll_comparison <- left_join(randstrobes, mixedrandstrobes70, by = c("V1", "V2")) %>% 
  left_join(altstrobes, by = c("V1", "V2")) %>% 
  mutate(mp_mixed = V3.y/V3.x, mp_alt = V3/V3.x, 
         sc_mixed = V4.y/V4.x, sc_alt = V4/V4.x, 
         mc_mixed = V5.y/V5.x, mc_alt = V5/V5.x,
         esize_mixed = V6.y/V6.x, esize_alt = V6/V6.x) %>% 
  dplyr::select("length"=V2,mp_mixed, mp_alt, sc_mixed, sc_alt, mc_mixed, mc_alt, esize_mixed, esize_alt)


ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = mp_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mp_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = mp_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mp_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  scale_y_continuous(trans = log2_trans(), breaks = c(0.9, 1.0, 1.1, 1.2, 1.3, 1.4))+
  labs(x = "Length [bp]",
       y = "Matches [log2 - Fold Change]")
ggsave("../output/figs/[Fig4.1] Matches.png", height = 4, width = 4)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = sc_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = sc_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = sc_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = sc_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  scale_y_continuous(trans = log2_trans(), breaks = c(0.9, 1.0, 1.1, 1.2, 1.3, 1.4))+
  labs(x = "Length [bp]",
       y = "Sequence Coverage [log2 - Fold Change]")
ggsave("../output/figs/[Fig4.1] Sequence Coverage.png", height = 4, width = 4)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = mc_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mc_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = mc_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = mc_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  scale_y_continuous(trans = log2_trans(), breaks = c(0.8, 0.9, 1.0, 1.1, 1.2))+
  labs(x = "Length [bp]",
       y = "Match Coverage [log2 - Fold Change]")
ggsave("../output/figs/[Fig4.1] Match Coverage.png", height = 4, width = 4)

ggplot(results_coll_comparison)+
  geom_point(aes(x = length, y = esize_mixed), col = "blue", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = esize_mixed), col = "blue", size = 0.4, se = F)+
  geom_point(aes(x = length, y = esize_alt), col = "#E76BF3", size= 0.2, alpha = 0.2)+
  geom_smooth(aes(x = length, y = esize_alt), col = "#E76BF3", size = 0.4, se = F)+
  geom_line(aes(x=length, y = 1), col = "#00B0F6")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = "none")+
  scale_y_continuous(trans = log2_trans(), breaks = c(0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2))+
  labs(x = "Length [bp]",
       y = "Expected Island Size [log2 - Fold Change]")
ggsave("../output/figs/[Fig4.1] Expected Island Size.png", height = 4, width = 4)
```




```{r}
n_protocol <- results_coll %>% group_by(method, strobe_fraction) %>% summarise(tot_length = sum(length))

results_coll_summarized <- results_coll %>% 
  mutate(mp = mp * length, sc = sc * length, mc = mc * length, esize = esize * length) %>% 
  group_by(method, strobe_fraction) %>% summarise(length = mean(length), mp = sum(mp), sc = sum(sc), mc = sum(mc), esize = sum(esize)) %>% 
  left_join(n_protocol, by=c("method", "strobe_fraction")) %>% 
  mutate(mp = mp/tot_length, sc = sc/tot_length, mc = mc/tot_length, esize = esize/tot_length)
results_coll_summarized$method <- factor(results_coll_summarized$method, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse"))

results_coll_summarized %>% filter(strobe_fraction == 0 | strobe_fraction == 100)
results_coll_summarized %>% filter(method == "randstrobes")
```


```{r}
p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = mp, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = mp, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")
ggsave("../output/figs/[Fig3] Matches.png", height = 3, width = 3)

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = sc, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = sc, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")
ggsave("../output/figs/[Fig3] Sequence Coverage.png", height = 3, width = 3)

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = mc, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = mc, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")
ggsave("../output/figs/[Fig3] Match Coverage.png", height = 3, width = 3)

p <- ggplot(results_coll_summarized)+
  geom_point(aes(x = strobe_fraction, y = esize, col = method, shape = method))+
  geom_line(aes(x = strobe_fraction, y = esize, col = method))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size")
ggsave("../output/figs/[Fig3] Expected Island Size.png", height = 3, width = 3)
```

