---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
```

```{r}
results_sim <- read.table(file = "../output/data tables/matching_analysis_simulated", sep = "&", header = F)
colnames(results_sim) <- c("protocol", "order", "setting", "strobe_fraction", "matches", "sequence_coverage", "match_coverage", "gaps", "mutation_rate")
results_sim <- results_sim %>% mutate(protocol = gsub("mixed", "", protocol))
results_sim$protocol <- factor(results_sim$protocol, levels = c("kmers", "minstrobes", "hybridstrobes", "randstrobes", "altstrobes", "spaced_kmers_dense", "spaced_kmers_sparse"))
results_sim
```

```{r}
p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")))+
  geom_point(aes(x = 100*strobe_fraction, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")+
  facet_wrap(order~mutation_rate, scales = "free")
p +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/[Fig2] Matches.png", height = 7, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) )+
  geom_point(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")+
  facet_wrap(order~mutation_rate, scales = "free")
p +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/[Fig2] Sequence Coverage.png", height = 7, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) )+
  geom_point(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")+
  facet_wrap(order~mutation_rate, scales = "free")
p +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/[Fig2] Match Coverage.png", height = 7, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) )+
  geom_point(aes(x = 100*strobe_fraction, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(order~mutation_rate, scales = "free")
p +
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Order", breaks = NULL, labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/[Fig2] Expected Island Size.png", height = 7, width = 7)
```
```{r}
p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = matches, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = matches, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Matches [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))

ggsave("../output/figs/[Fig2] Matches (order2).png", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = sequence_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Sequence Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/[Fig2] Sequence Coverage (order2).png", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = match_coverage, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Match Coverage [%]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/[Fig2] Match Coverage (order2).png", height = 3, width = 7)

p <- ggplot(results_sim %>% filter(!protocol %in% c("spaced_kmers_dense", "spaced_kmers_sparse")) %>% filter(order == 2) )+
  geom_point(aes(x = 100*strobe_fraction, y = gaps, col = protocol, shape = protocol))+
  geom_line(aes(x = 100*strobe_fraction, y = gaps, col = protocol))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(legend.position = "none")+
  scale_shape_manual(values = c(16,22,23,24,25))+
  labs(x = "Strobe Fraction [%]",
       y = "Expected Island Size [bp]")+
  facet_wrap(~mutation_rate, scales = "free")
p +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Mutation Rate", breaks = NULL, labels = NULL))
ggsave("../output/figs/[Fig2] Expected Island Size (order2).png", height = 3, width = 7)
```

