

```{r}
library("tidyverse")
library(viridis)
```

```{r}
results_uniqueness <- read.table(file = "../output/data tables/uniqueness.csv", header = TRUE, sep = ",")
results_uniqueness
results_uniqueness$Method = factor(results_uniqueness$Method, levels=c('kmers', 'mixedminstrobes2', 'mixedminstrobes3', 'mixedhybridstrobes2', 'mixedhybridstrobes3', 'mixedrandstrobes2', 'mixedrandstrobes3', 'mixedaltstrobes2'))
```


```{r}
ggplot(results_uniqueness %>% filter(Method != "kmers"))+
  geom_line(aes(x = k, y = unique, group= strobefraction, col = strobefraction))+
  facet_wrap(~ Method)+
  scale_color_viridis(discrete = FALSE, option = "B")+
  ylab("% unique")+
  scale_x_continuous(limits = c(18, 36))

ggsave("../output/figs/[Fig4] uniqueness_mixed.png", width = 6, height = 4.4)

```
```{r}
results_uniqueness2 <- results_uniqueness %>% filter(Method == "kmers" | strobefraction == 100) %>% mutate(Method = str_replace(Method, "mixed",""))
results_uniqueness2$Method = factor(results_uniqueness2$Method, levels=c('kmers', 'minstrobes2', 'minstrobes3', 'hybridstrobes2', 'hybridstrobes3', 'randstrobes2', 'randstrobes3', 'altstrobes2'))                                                                                                           

ggplot(results_uniqueness2)+
  geom_line(aes(x = k, y = unique, col = Method, linetype = Method))+
  geom_point(aes(x = k, y = unique, col = Method, shape = Method))+
  scale_linetype_manual(values=c("solid", "longdash", "dotted", "longdash", "dotted", "longdash", "dotted", "longdash"))+
  scale_shape_manual(values = c(16,22,22,23,23,24,24,25))+
  ylab("% unique")+
  scale_x_continuous(limits = c(18, 36))

ggsave("../output/figs/[Fig4] uniqueness.png", width = 6, height = 4.4)
```

